print(f"     /~\\")
print(f"    ( oo|")
print(f"    _\=/_")
print(f"   /  _  \\")
print(f"  //|/.\|\\\\")
print(f" ||  \ /  ||")
print(f"============")
print(f"|          |")
print(f"|          |")
print(f"|          |")